from typing import TypedDict, List
from langchain_core.documents import Document


# state for the agent
class RAGState(TypedDict):
    query: str
    retrieved_docs: List[Document]  # from vector db
    reranked_docs: List[Document]
    response: dict
    route: str  # "VECTOR_DB or RDBMS"
    route_selection_reason: str
    generated_sql: str  # SQL generated by nl2sql
    sql_result: str  # output of raw sql execution result
    user_id: str  # who is asking - the mem0 memory owner
    memory_context: str  # facts recalled from mem0, injected into prompts